name = "ucan-kms"
main = "dist/worker.mjs"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-07-15"

[build]
command = "npm run build"
outdir = "dist"

#### STAGING ENVIRONMENT CONFIGURATION

# Staging Environment-specific observability settings
[env.staging.observability]
enabled = true

[env.staging]
workers_dev = true
account_id = "fffa4b4363a7e5250af8357087263b3a"
#route = { pattern = "https://staging.kms.storacha.link/*", zone_id = "TBD" }
r2_buckets = []
kv_namespaces = [
  { binding = "KMS_RATE_LIMIT_KV", id = "3fd03e7be796478fbb92c2aa6a62f767" }
]

# Staging Environment-specific variables
[env.staging.vars]
ENVIRONMENT = "staging"
UCAN_KMS_SERVICE_DID = "did:web:staging.kms.storacha.link"
# REVOCATION_STATUS_SERVICE_URL = "https://up.web3.storage"
# SUBSCRIPTION_PLAN_SERVICE_URL = "https://up.web3.storage"

# Staging Environment-specific FEATURE FLAGS
FF_DECRYPTION_ENABLED = "true"
FF_KMS_RATE_LIMITER_ENABLED = "true"

# Staging Environment-specific KMS CONFIG
GOOGLE_KMS_BASE_URL = "https://cloudkms.googleapis.com/v1"
GOOGLE_KMS_PROJECT_ID = "storacha-staging"
GOOGLE_KMS_LOCATION = "global"
GOOGLE_KMS_KEYRING_NAME = "private-gateway"

# Staging Environment-specific SECRETS
# Secrets are not defined in wrangler.toml
# Use wrangler secret put commands or .dev.vars file for local development
# [[env.staging.unsafe.bindings]]
# name = "GOOGLE_KMS_TOKEN"
# type = "secret"
# secret = "GOOGLE_KMS_TOKEN"
# 
# [[env.staging.unsafe.bindings]]
# name = "UCAN_KMS_PRINCIPAL_KEY"
# type = "secret"
# secret = "UCAN_KMS_PRINCIPAL_KEY"

#### FFORBECK ENVIRONMENT CONFIGURATION
# Forbeck Environment-specific observability settings
[env.fforbeck.observability]
enabled = true

[env.fforbeck]
workers_dev = true
account_id = "fffa4b4363a7e5250af8357087263b3a"
r2_buckets = []
kv_namespaces = [
  { binding = "KMS_RATE_LIMIT_KV", id = "802300fd46a642e7bcdd65dc7df51691" }
]

# Forbeck Environment-specific variables
[env.fforbeck.vars]
ENVIRONMENT = "development"
UCAN_KMS_SERVICE_DID = "did:web:dev.kms.storacha.link"
# REVOCATION_STATUS_SERVICE_URL = "https://up.web3.storage"
# SUBSCRIPTION_PLAN_SERVICE_URL = "https://up.web3.storage"

# Forbeck Environment-specific FEATURE FLAGS
FF_DECRYPTION_ENABLED = "true"
FF_KMS_RATE_LIMITER_ENABLED = "true"

# Development Environment-specific KMS CONFIG
GOOGLE_KMS_BASE_URL = "https://cloudkms.googleapis.com/v1"
GOOGLE_KMS_PROJECT_ID = "storacha-staging"
GOOGLE_KMS_LOCATION = "global"
GOOGLE_KMS_KEYRING_NAME = "ucan-kms-staging-keyring"

# Forbeck Environment-specific SECRETS
# Secrets are not defined in wrangler.toml
# Use wrangler secret put commands or .dev.vars file for local development
# [[env.fforbeck.unsafe.bindings]]
# name = "GOOGLE_KMS_TOKEN"
# type = "secret"
# secret = "GOOGLE_KMS_TOKEN"
# 
# [[env.fforbeck.unsafe.bindings]]
# name = "UCAN_KMS_PRINCIPAL_KEY"
# type = "secret"
# secret = "UCAN_KMS_PRINCIPAL_KEY"