name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # This specifies which files to bump
          release-type: node
          # Ensures tags like v1.2.3 (not ucan-kms-v1.2.3)
          include-component-in-tag: false

      # The logic below handles the case where a release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: '22' # LTS

      - name: Setup pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        if: ${{ steps.release.outputs.release_created }}
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --no-frozen-lockfile

      - name: Run type check
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run type-check

      - name: Build project
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build

      - name: Run tests
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run test:unit
